swagger: '2.0'
info:
    version: "20161028"
    title: Bridge Server API
host: webservices.sagebridge.org
basePath: /
securityDefinitions:
    BridgeSecurity:
        type: apiKey
        in: header
        name: Bridge-Session
schemes:
    - https
consumes:
    - application/json
produces:
    - application/json
paths:
    $ref: ./paths/index.yml
definitions:
    $ref: ./definitions/index.yml
responses:
    $ref: ./responses/index.yml