get:
    operationId: getSchedulerConfig
    summary: Get a scheduler config
    tags: 
        - _For Admins
    security:
        - BridgeSecurity: []
    parameters:
        - $ref: ../../index.yml#/parameters/scheduleId
    responses:
        200:
            description: OK
            schema:
                $ref: ../../definitions/master_scheduler_config.yml
        401:
            $ref: ../../responses/401.yml
        403:
            $ref: ../../responses/403_not_admin.yml
post:
    operationId: updateSchedulerConfig
    summary: Update a scheduler config
    tags: 
        - _For Admins
    security:
        - BridgeSecurity: []
    parameters:
        - $ref: ../../index.yml#/parameters/scheduleId
        - name: MasterSchedulerConfig
          required: true
          in: body
          schema:
            $ref: ../../definitions/master_scheduler_config.yml
    responses:
        200:
            description: OK
            schema:
                $ref: ../../definitions/master_scheduler_config.yml
        401:
            $ref: ../../responses/401.yml
        403:
            $ref: ../../responses/403_not_admin.yml
delete:
    operationId: deleteSchedulerConfig
    summary: Delete a scheduler config
    tags: 
        - _For Admins
    security:
        - BridgeSecurity: []
    parameters:
        - $ref: ../../index.yml#/parameters/scheduleId
    responses:
        200:
            $ref: ../../responses/200_message.yml
        401:
            $ref: ../../responses/401.yml
        403:
            $ref: ../../responses/403_not_admin.yml
