type: object
readOnly: true
allOf:
    - $ref: ./resource_list.yml
    - properties:
        items:
            type: array
            readOnly: true
            x-nullable: false
            items:
                $ref: ../app_config.yml
