type: object
readOnly: true
required:
    - items
properties:
    items:
        type: array
        items:
            $ref: ../app_config.yml
    type:
        type: string
        readOnly: true
        description: "ResourceList"
