type: object
readOnly: true
allOf:
    - $ref: './resource_list.yml'
    - required:
        - items
    - properties:
        items:
            type: array
            items:
                $ref: ../app_config_element.yml
        type:
            type: string
            readOnly: true
            description: "ResourceList"