get:
    operationId: getAppConfigForStudy
    summary: |
        Get the app config for the current version of the app making the request. 
    description: |
        Although this call uses Bridge's common filtering framework (see https://developer.sagebridge.org/articles/study_design.html#filtering), the request does not require authentication, so only User-Agent and Accept-Language filtering criteria are used.
    tags:
        - Studies
        - Public
        - _For Consented Users
    security:
        - BridgeSecurity: []
    parameters:
        - $ref: ../../index.yml#/parameters/studyId
    responses:
        200:
            description: OK
            schema:
                $ref: ../../definitions/app_config.yml
