get:
    operationId: getUsersAppConfig
    summary: |
        Get an app config for a specific client based on criteria such as the 
        application version and platform.
    tags:
        - AppConfigs
        - _For Consented Users
    security:
        - BridgeSecurity: []
    description: |
        Get all the app configuration objects for this study.
    responses:
        200:
            description: OK
            schema:
                $ref: ../../definitions/app_config.yml
        401:
            $ref: ../../responses/401.yml
        410:
            $ref: ../../responses/410.yml
        412:
            $ref: ../../responses/412.yml
