get:
    operationId: getAppConfig
    summary: Get an app config
    tags:
        - App Configs
        - _For Developers
    security:
        - BridgeSecurity: []
    description: |
        Get an configuration object for this app.
    parameters:
        - $ref: ../../index.yml#/parameters/guid
    responses:
        200:
            description: OK
            schema:
                $ref: ../../definitions/app_config.yml
        401:
            $ref: ../../responses/401.yml
        403:
            $ref: ../../responses/403_not_developer.yml
post:
    operationId: updateAppConfig
    summary: Update an existing app config
    tags:
        - App Configs
        - _For Developers
    security:
        - BridgeSecurity: []
    description: |
        Update an existing app configuration.
    parameters:
        - $ref: ../../index.yml#/parameters/guid
        - name: AppConfig
          in: body
          description: Updated app configuration 
          required: true
          schema:
              $ref: ../../definitions/app_config.yml
    responses:
        200:
            description: OK
            schema:
                $ref: ../../definitions/guid_version_holder.yml
        401:
            $ref: ../../responses/401.yml
        403:
            $ref: ../../responses/403_not_developer.yml
delete:
    operationId: deleteAppConfig
    summary: Delete an app config
    tags:
        - App Configs
        - _For Developers
        - _For Admins
    security:
        - BridgeSecurity: []
    description: |
        Delete an existing configuration object.
    parameters:
        - $ref: ../../index.yml#/parameters/guid
        - $ref: ../../index.yml#/parameters/physical
    responses:
        200:
            description: OK
            schema:
                $ref: ../../definitions/message.yml
        401:
            $ref: ../../responses/401.yml
        403:
            $ref: ../../responses/403_not_admin_developer.yml