get:
    operationId: getAppConfigElement
    summary: Get an app config element
    tags:
        - AppConfigs
        - _For Developers
    security:
        - BridgeSecurity: []
    description: |
        Get an app configuration element for this app.
    parameters:
        - $ref: ../../index.yml#/parameters/id
        - $ref: ../../index.yml#/parameters/revision
    responses:
        200:
            description: OK
            schema:
                $ref: ../../definitions/app_config_element.yml
        401:
            $ref: ../../responses/401.yml
        403:
            $ref: ../../responses/403_not_developer.yml
post:
    operationId: updateAppConfigElement
    summary: Update an existing app config element
    tags:
        - AppConfigs
        - _For Developers
    security:
        - BridgeSecurity: []
    description: |
        Update an existing app configuration element.
    parameters:
        - $ref: ../../index.yml#/parameters/id
        - $ref: ../../index.yml#/parameters/revision
        - name: AppConfigElement
          in: body
          description: Updated app configuration element
          required: true
          schema:
              $ref: ../../definitions/app_config_element.yml
    responses:
        200:
            description: OK
            schema:
                $ref: ../../definitions/version_holder.yml
        401:
            $ref: ../../responses/401.yml
        403:
            $ref: ../../responses/403_not_developer.yml
delete:
    operationId: deleteAppConfigElement
    summary: Delete an app config element
    tags:
        - AppConfigs
        - _For Developers
        - _For Admins
    security:
        - BridgeSecurity: []
    description: |
        Delete an existing configuration element.
    parameters:
        - $ref: ../../index.yml#/parameters/id
        - $ref: ../../index.yml#/parameters/revision
        - $ref: ../../index.yml#/parameters/physical
    responses:
        200:
            description: OK
            schema:
                $ref: ../../definitions/message.yml
        401:
            $ref: ../../responses/401.yml
        403:
            $ref: ../../responses/403_not_admin_developer.yml