type: object
description: A pointer to a configuration element.
required:
    - id
    - revision
properties:
    id:
        type: string
        description: Schema ID
        x-nullable: false
    revision:
        type: integer
        format: int64
        description: Revision number
        x-nullable: false
    type:
        type: string
        readOnly: true
        description: "ConfigReference"
        x-nullable: false
