description: |
    Configurations to setup a report scheduler.
type: object
required:
    - scheduleId
properties:
    scheduleId:
        type: string
        description: schedule identifier
        x-nullable: false
    cronSchedule:
        type: string
        description: Cron expression indicating when the schedule should be run.
    requestTemplate:
        type: object
        description: An arbitrary JSON object containing template for the request to be sent to the configured SQS queue. 
        x-nullable: false
    sqsQueueUrl:
        type: string
        description: SQS queue URL to send requests to
        x-nullable: false    
    version:
        type: integer
        format: int64
        description: |
            The optimistic locking version of the survey. This value must be submitted as part of the next update of the model. If it does not match the value on the server, a 409 error (Conflict) will prevent the update from occurring.
    type:
        type: string
        readOnly: true
        description: "MasterSchedulerConfig"
        x-nullable: false